"""Measure where the detector is weak, and write BLINDSPOTS.md.

    docker compose exec -T backend python -m scripts.measure_blindspots \
        --stdout > BLINDSPOTS.md

Diagnostic. It builds three cases designed to sit where the Phase 3 scoring is
weakest, runs the real detector over them, and grades the generated case files
for fabrication and miscalibration.

The robustness cases are inserted, measured, and rolled back - they never enter
the corpus, so the held-out numbers stay untouched and every stored transaction
still traces to a real Razorpay order.

Nothing here produces guidance for avoiding detection. The output is a
measurement of our own blind spots, written down so they can be argued with
rather than discovered by someone else.
"""

from __future__ import annotations

import argparse
import pathlib
import sys
import textwrap

from app.db import SessionLocal
from detection.config import DetectorConfig
from evaluation.blindspots import BlindspotReport, measure
from evaluation.explanation_quality import (
    FREE_NUMBER_CEILING,
    QualityReport,
    grade_all,
)
from evaluation.metrics import latest_stored

OK = "[ok]"


def default_output() -> pathlib.Path | None:
    """Where BLINDSPOTS.md belongs, or None if the repo root is out of reach.

    Only `./backend` is mounted into the container, so the repo root simply is
    not visible from there and no path arithmetic can conjure it. Rather than
    writing to a plausible-looking path on the container's ephemeral
    filesystem - which silently produced nothing for a while - this returns
    None and `main` directs the caller to the `--stdout` form instead.
    """
    for parent in pathlib.Path(__file__).resolve().parents:
        if (parent / "CLAUDE.md").is_file():
            return parent / "BLINDSPOTS.md"
    return None


def wrap(body: str, width: int = 78) -> str:
    return "\n".join(textwrap.wrap(" ".join(body.split()), width=width))


def render(
    blind: BlindspotReport, quality: QualityReport, holdout: dict | None
) -> str:
    out: list[str] = []
    a = out.append

    a("# Where RingSentinel is weak")
    a("")
    a(wrap(
        "This is a diagnostic, written down deliberately. The held-out result in "
        "CLAUDE.md is 4/4 rings with zero false flags, and a number that clean "
        "invites the reasonable suspicion that the test was easy. It partly was: "
        "the held-out rings came from the same generator as the tuning rings. "
        "The three cases below were built instead to sit exactly where the "
        "scoring is weakest, and the results are reported as measured - nothing "
        "was tuned in response to them."
    ))
    a("")
    a(f"*Generated by `scripts/measure_blindspots.py` on "
      f"{blind.run_at.strftime('%Y-%m-%d')} · detector "
      f"{blind.detector_version} · flag threshold {blind.threshold} · "
      f"confidence threshold {blind.confident_threshold}.*")
    a("")
    a("---")
    a("")

    # ---- headline comparison ------------------------------------------
    a("## Against the held-out set")
    a("")
    a("| | Held-out (Phase 6) | Robustness cases |")
    a("|---|---|---|")
    if holdout:
        h = holdout["headline"]
        c = holdout["confusion"]
        a(f"| Recall | {h['recall']:.0%} "
          f"({c['rings_detected']}/{c['rings_total']} rings) | "
          f"{blind.recall:.0%} ({blind.rings_detected}/{len(blind.rings)} rings) |")
        a(f"| Precision | {h['precision']:.0%} | {blind.precision:.0%} |")
        a(f"| False flags | {c['false_positives_clusters']} | {blind.false_flags} |")
    else:
        a(f"| Recall | (not recorded) | {blind.recall:.0%} |")
        a(f"| Precision | (not recorded) | {blind.precision:.0%} |")
        a(f"| False flags | (not recorded) | {blind.false_flags} |")
    a("")
    a(wrap(
        "The two are not the same measurement and should not be read as one. "
        "Held-out is an unbiased estimate on unseen data of the same shape. "
        "This is a targeted probe at known weak points, on three cases rather "
        "than twelve - too small a sample to put a confidence interval on, and "
        "useful for direction rather than for a headline."
    ))
    a("")

    # The expected result was a drop. Saying so is the point of the exercise.
    missed = [o for o in blind.rings if not o.flagged]
    if not missed and not blind.false_flags:
        a("### This came out better than expected. Read it sceptically.")
        a("")
        a(wrap(
            "These cases were written to make the detector fail, and the "
            "honest prediction going in was that they would. They did not. "
            "That result is reported exactly as measured - nothing was tuned "
            "in response to it, and nothing was retried until it looked "
            "better - but three passes are not evidence of robustness, for two "
            "reasons worth stating before anyone quotes the number."
        ))
        a("")
        a(wrap(
            "**The cases share an author with the detector.** They probe the "
            "weaknesses we already knew about, because those are the ones we "
            "were able to think of. An adversary who did not design the "
            "scoring would probe elsewhere, and the blind spot that matters is "
            "by definition the one not on this list."
        ))
        a("")
        a(wrap(
            "**Three cases cannot carry a percentage.** \"100% recall\" here "
            "means two rings out of two. It is reported as a fraction "
            "throughout for that reason, and it should not be set beside the "
            "held-out figure as though the two were comparable."
        ))
        a("")

    ambiguous = [
        o for o in blind.rings
        if o.flagged and o.score is not None
        and o.score < blind.confident_threshold
    ]
    if ambiguous:
        names = ", ".join(o.case.title.lower() for o in ambiguous)
        a(wrap(
            f"There is one real finding underneath the pass marks. The "
            f"{names} cleared the flag threshold but not the confidence "
            f"threshold, landing in `needs_review` rather than `pending`. A "
            f"genuine ring paced like people is therefore found, but found "
            f"weakly - which is the same weakness the Phase 6 evaluation "
            f"reported from the opposite direction, where human-cadence rings "
            f"scored 0.503 against 0.776 for agent-cadence ones. Two "
            f"independent measurements agreeing on where the detector is thin "
            f"is worth more than either passing on its own."
        ))
        a("")

    a("---")
    a("")

    # ---- per case -------------------------------------------------------
    a("## The three cases")
    a("")
    for outcome in blind.outcomes:
        case = outcome.case
        verdict = "as intended" if outcome.correct else "**NOT as intended**"
        a(f"### {case.title}")
        a("")
        a(f"**Question:** {wrap(case.question, 74)}")
        a("")
        expected = "should be flagged" if case.should_be_flagged else "should NOT be flagged"
        actual = "flagged" if outcome.flagged else "not flagged"
        a(f"- Expectation: {expected}")
        a(f"- Result: **{actual}** — {verdict}")
        if outcome.flagged:
            a(f"- Score {outcome.score} → `{outcome.status}` · cadence "
              f"`{outcome.cadence}` · {outcome.accounts_in_cluster} of "
              f"{outcome.accounts_total} accounts captured")
        a("")
        a(f"**What it reveals:** {wrap(outcome.reading, 74)}")
        a("")

    a("---")
    a("")

    # ---- explanation quality --------------------------------------------
    a("## Explanation quality")
    a("")
    a(f"**{quality.passes} of {quality.total} case files pass all three "
      f"criteria ({quality.pass_rate:.0%}).**")
    a("")
    if quality.total < quality.requested_sample:
        a(wrap(
            f"The sample is {quality.total}, not {quality.requested_sample}: that "
            f"is every case file the corpus currently holds. Reporting the "
            f"smaller real sample is better than padding it to a round number."
        ))
        a("")
    a("| Criterion | Method | Failures |")
    a("|---|---|---|")
    a(f"| Cites only true evidence | mechanical string match against "
      f"`evidence_json` | {quality.failing('grounded')} |")
    a(f"| Avoids overclaiming | mechanical: certainty language on a cluster "
      f"inside the ambiguous band | {quality.failing('calibrated')} |")
    a(f"| Action fits the evidence | mechanical: action checked against the "
      f"score bands | {quality.failing('action_fits')} |")
    a("")
    a(wrap(
        "Graded mechanically, not by a model. Asking Claude to grade Claude "
        "would have been cheaper to build and much weaker as evidence - a model "
        "evaluating its own output shares its own blind spots. Every entity "
        "reference and every count a case file asserts is matched against the "
        "cluster's stored evidence, so 'no fabricated attributes' is a "
        "verifiable claim rather than an opinion."
    ))
    a("")
    a(wrap(
        "The limit of that approach, stated plainly: mechanical checks catch "
        "fabrication and miscalibration. They cannot tell whether an "
        "explanation is genuinely insightful. This measures honesty, not "
        "quality."
    ))
    a("")
    a("### How much the grounding check actually bites")
    a("")
    a(wrap(
        f"A pass rate is only worth reading if the checker could have failed "
        f"something, so here is its reach. Across these {quality.total} case "
        f"files the grader examined **{quality.numbers_asserted} asserted "
        f"numbers**, of which **{quality.numbers_constrained}** were genuinely "
        f"constrained against the cluster's evidence. The remaining "
        f"{quality.numbers_asserted - quality.numbers_constrained} fall below "
        f"{FREE_NUMBER_CEILING} and are treated as ordinary English - \"one "
        f"card\", \"two of the four\" - rather than as claims. Entity "
        f"references are checked in full, with no such allowance."
    ))
    a("")
    a(wrap(
        "That the grader can fail a case file at all is itself verified rather "
        "than assumed. `scripts/verify_explanation_grader.py` feeds it one "
        "honest case file and four broken ones - a fabricated entity "
        "reference, a fabricated count, certainty language on an ambiguous "
        "cluster, and an action contradicting the score - and requires each to "
        "be caught by the criterion meant to catch it. This is not a "
        "precaution in the abstract: the tokeniser shipped with its word "
        "boundaries corrupted into control characters, matched no digits "
        "whatsoever, and passed a case file claiming 9,471 transactions. The "
        "pass rate did not reveal that. The self-test did."
    ))
    a("")

    failures = [s for s in quality.scored if not s.passed]
    if failures:
        a("### Case files that failed")
        a("")
        for score in failures[:8]:
            a(f"- `{score.cluster_id[:8]}` (score {score.score:.3f}): "
              f"{'; '.join(score.findings)}")
        a("")

    a("---")
    a("")
    a("## Scope and method")
    a("")
    a(wrap(
        "The robustness cases are inserted through the real ingest path, scored "
        "by the real detector, measured, and then rolled back. Nothing "
        "persists. That keeps two properties intact: every stored transaction "
        "still traces to a real Razorpay test-mode order, and the held-out "
        "numbers are not disturbed by diagnostic data."
    ))
    a("")
    a(wrap(
        "No guidance for avoiding detection is produced anywhere in this "
        "repository, and all traffic runs against a local test-mode instance "
        "only. These cases exist to measure our own blind spots, not to "
        "circumvent anything."
    ))
    a("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Measure detector blind spots and write BLINDSPOTS.md."
    )
    parser.add_argument("--sample", type=int, default=15)
    parser.add_argument(
        "--stdout",
        action="store_true",
        help=(
            "Write the document to stdout instead of to a file, so it can be "
            "redirected from the host. The progress summary goes to stderr."
        ),
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=None,
        help="Explicit path for BLINDSPOTS.md.",
    )
    args = parser.parse_args()

    # Progress goes to stderr whenever the document owns stdout.
    log = sys.stderr if args.stdout else sys.stdout

    config = DetectorConfig()
    db = SessionLocal()
    try:
        print("Measuring robustness cases (inserted, scored, rolled back)…", file=log)
        blind = measure(db, config)

        print("Grading case files…", file=log)
        quality = grade_all(db, limit=args.sample, config=config)

        holdout = latest_stored(db, "holdout")
        document = render(blind, quality, holdout)

        destination = args.output or (None if args.stdout else default_output())
        if args.stdout:
            sys.stdout.write(document)
        elif destination is not None:
            destination.write_text(document, encoding="utf-8")

        # Console summary - the document is the artefact.
        print(file=log)
        print("=" * 70, file=log)
        for outcome in blind.outcomes:
            mark = OK if outcome.correct else "[MISS]"
            state = "flagged" if outcome.flagged else "not flagged"
            score = f" at {outcome.score}" if outcome.score else ""
            print(f"  {mark:<7} {outcome.case.title:<24} {state}{score}", file=log)
        print(file=log)
        print(f"  robustness recall    : {blind.recall:.0%} "
              f"({blind.rings_detected}/{len(blind.rings)} rings)", file=log)
        print(f"  robustness precision : {blind.precision:.0%} "
              f"({blind.false_flags} false flag(s))", file=log)
        print(f"  explanation quality  : {quality.passes}/{quality.total} "
              f"({quality.pass_rate:.0%}) pass all three criteria", file=log)
        print("=" * 70, file=log)

        if destination is not None:
            print(f"\n{OK} written to {destination}", file=log)
        elif not args.stdout:
            print(
                f"\n[!] The repo root is not visible from here - only ./backend "
                f"is mounted into the container, so there is nowhere to write "
                f"BLINDSPOTS.md.\n    Redirect it from the host instead:\n"
                f"      docker compose exec -T backend python -m "
                f"scripts.measure_blindspots --stdout > BLINDSPOTS.md",
                file=log,
            )
        print(f"{OK} nothing persisted - the corpus is unchanged", file=log)
        return 0
    finally:
        db.rollback()
        db.close()


if __name__ == "__main__":
    sys.exit(main())
